add exit code for authorization failure

diff --git a/bins/Download/osk_S2_download b/bins/Download/osk_S2_download
--- a/bins/Download/osk_S2_download
+++ b/bins/Download/osk_S2_download
@@ -84,9 +84,13 @@ while read line; do
 			echo "Download of ${UUID} completed"
 			i=3
 
+		elif grep -q "Authorization failed" ${TMP_DIR}/tmp_error;then
+
+			echo " Authorization failed"
+			exit 1
 		else
 				
-			echo " Connection problems, will try again in 5 minutes"
+			echo " Connection problems, will try to continue download in 5 minutes"
 			sleep 5m				
 		fi		
 
