doing various updates

diff --git a/bins/Download/ost_S1_ASF_download b/bins/Download/ost_S1_ASF_download
--- a/bins/Download/ost_S1_ASF_download
+++ b/bins/Download/ost_S1_ASF_download
@@ -116,65 +116,61 @@ while read line; do
 	ORB_DIR=`echo $line | awk -F "\;" '{print $3}' 2>/dev/null`
 	DATE=`echo $line | awk -F "\;" '{print $4}' 2>/dev/null`
 	SCENE=`echo $line | awk -F "\;" '{print $5}' 2>/dev/null`
-	mkdir -p ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/
 
-	# prepare a loop to avoid uncomplete data downloads
-	i=1
-	echo "bla" > ${TMP_DIR}/tmp_error
-	#do the loop
-	j=1
-	for(( i=1; i<=2; i++ ));do
+	# if statement for repeated downloads
+  if [ -f ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/.$SCENE.passed ];then
+		echo "Product already downloaded"
+	else
 
-		i=3
-		SECONDS=0
-		echo -ne " Downloading Product ${COUNT} of ${NR} (Granule: ${SCENE})... " | tee -a "${PROC_DIR}/.s1_dow_progress"
-		wget --show-progress --progress=dot -q -c -P ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/ "${LINK}" >> ${TMP_DIR}/log_download_${COUNT} 2>&1
-		WGET_ERR=$?
+		mkdir -p ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/
 
-		# wget --show-progress --progress=dot -q -c -P ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/ "${LINK}" >> ${TMP_DIR}/log_download_${COUNT} 2>&1; WGET_ERR=$?) &
-		#  for ((k=1; k<=3; k++));do
-		# 	# get the percentage
-		# 	PERC_DOW=$(cat ${TMP_DIR}/log_download_${COUNT} log_download_1 | tail -n 2 | head -n 1 | awk '{print $7}')
-		# 	echo -e "\e[0K\r Downloading Product ${COUNT} of ${NR} (Granule: ${SCENE})...${PERC_DOW} " | tee -a "${PROC_DIR}/.s1_dow_progress"
-		#
-		# 	if [ -z ${WGET_ERR} ];then
-		# 		k=5
-		# 		unset ${WGET_ERR}
-		# 	else
-		# 		k=1
-		# 	fi
-		# done
+		# prepare a loop to avoid uncomplete data downloads
+		i=1
+		echo "bla" > ${TMP_DIR}/tmp_error
+		#do the loop
+		j=1
+		for(( i=1; i<=2; i++ ));do
 
+			i=3
+			SECONDS=0
+			echo -ne " Downloading Product ${COUNT} of ${NR} (Granule: ${SCENE})... " | tee -a "${PROC_DIR}/.s1_dow_progress"
+			echo "wget --show-progress --progress=dot -q -c -P ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/ "${LINK}""
+			wget --show-progress --progress=dot -q -c -P ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/ "${LINK}" >> ${TMP_DIR}/log_download_${COUNT} 2>&1
+			WGET_ERR=$?
 
-		if [ ${WGET_ERR} == 6 ]; then
-			echo -e ""
-			echo " Username/Password Authentication Failed."  | tee -a "${PROC_DIR}/.s1_dow_progress"
-			rm -rf ${TMP_DIR} && exit 2
-		elif [ ${WGET_ERR} -ne 0 ]; then
-			i=1 && echo -e " failed, having another try."  | tee -a "${PROC_DIR}/.s1_dow_progress"
-			j=$(expr $j + 1)
-			if [ $j -gt 50 ];then
+			if [ ${WGET_ERR} == 6 ]; then
 				echo -e ""
-				echo " Tried more then 50 times downloading the scene. Exiting because of download problems."  | tee -a "${PROC_DIR}/.s1_dow_progress"
-				rm -rf ${TMP_DIR} && exit 3
-			fi
-		else
-				duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"  | tee -a "${PROC_DIR}/.s1_dow_progress"
-
-				SECONDS=0
-				echo -ne " Checking for Zip archive file integrity..."  | tee -a "${PROC_DIR}/.s1_dow_progress"
-				if 7z t ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/${SCENE}.zip | grep "Everything is Ok" > /dev/null;then
-					duration=$SECONDS && echo -e " passed ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"  | tee -a "${PROC_DIR}/.s1_dow_progress"
-				else
-					i=1
-					duration=$SECONDS && echo -e " failed. Will restart download. ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"  | tee -a "${PROC_DIR}/.s1_dow_progress"
-					rm -f ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/${SCENE}.zip
+				echo " Username/Password Authentication Failed."  | tee -a "${PROC_DIR}/.s1_dow_progress"
+				rm -rf ${TMP_DIR}
+				exit 2
+			elif [ ${WGET_ERR} -ne 0 ]; then
+				i=1 && echo -e " failed, having another try."  | tee -a "${PROC_DIR}/.s1_dow_progress"
+				j=$(expr $j + 1)
+				if [ $j -gt 50 ];then
+					echo -e ""
+					echo " Tried more then 50 times downloading the scene. Exiting because of download problems."  | tee -a "${PROC_DIR}/.s1_dow_progress"
+					rm -rf ${TMP_DIR}
+					exit 3
 				fi
+			else
+					duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"  | tee -a "${PROC_DIR}/.s1_dow_progress"
 
-		fi
+					SECONDS=0
+					echo -ne " Checking for Zip archive file integrity..."  | tee -a "${PROC_DIR}/.s1_dow_progress"
+					if 7z t ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/${SCENE}.zip | grep "Everything is Ok" > /dev/null;then
+						echo "download passed" > ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/.$SCENE.passed
+						duration=$SECONDS && echo -e " passed ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"  | tee -a "${PROC_DIR}/.s1_dow_progress"
+					else
+						i=1
+						duration=$SECONDS && echo -e " failed. Will restart download. ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"  | tee -a "${PROC_DIR}/.s1_dow_progress"
+						rm -f ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/${SCENE}.zip
+					fi
 
-	done
+			fi
 
+		done
+
+	fi # close the existing file loop
 	COUNT=`expr ${COUNT} + 1`
 
 done < ${TMP_DIR}/tmp_list
