major changes in shiny GUI

diff --git a/bins/Download/ost_S1_ASF_download b/bins/Download/ost_S1_ASF_download
--- a/bins/Download/ost_S1_ASF_download
+++ b/bins/Download/ost_S1_ASF_download
@@ -23,57 +23,52 @@
 #-------------------------------------------------------------------------------------------
 # 	0.1 Check for right usage & set up basic Script Variables
 if [ "$#" == "3" ]; then
-	echo -e "---------------------------------------------------------------------------"
-	echo -e " Open Foris SAR Toolkit, version ${OSK_VERSION}"
-	echo -e " Download Sentinel-1 data from ASF server using an OFST inventory shapefile"
-	echo -e "---------------------------------------------------------------------------"
 
-	export WGETRC=`readlink -f $3`
-  cd $1
-  PROC_DIR=`pwd`
-	TMP_DIR=${PROC_DIR}/.TMP
-	rm -rf ${TMP_DIR} > /dev/null
-	mkdir -p ${TMP_DIR}
 	# source libs
 	source ${OPENSARKIT}/lib/helpers_source
 
+	export WGETRC=`readlink -f $3`
+	cd $1
+	PROC_DIR=`pwd`
+	TMP_DIR=${PROC_DIR}/.TMP
+	mkdir -p ${TMP_DIR}
+
+	echo -e "---------------------------------------------------------------------------" | tee ${PROC_DIR}/.s1_dow_progress
+	echo -e " Open SAR Toolkit, version ${OST_VERSION}"  | tee -a ${PROC_DIR}/.s1_dow_progress
+	echo -e " Download Sentinel-1 data from ASF server using an OST inventory shapefile"  | tee -a ${PROC_DIR}/.s1_dow_progress
+	echo -e "---------------------------------------------------------------------------"  | tee -a ${PROC_DIR}/.s1_dow_progress
 
 elif [ "$#" != "2" ]; then
 
-	echo -e "----------------------------------"
-	echo -e " Open Foris SAR Toolkit, version ${OSK_VERSION}"
-	echo -e " Download ALOS data from an ASF server using an OFST inventory shapefile"
-	echo -e "----------------------------------"
-	echo -e ""
-	echo -e "----------------------------------"
-	echo -e " Software dependencies:"
-	echo -e "	- aria2"
-	echo -e "	- ogrinfo"
-	echo -e "----------------------------------"
+	echo -e "---------------------------------------------------------------------------"
+	echo -e " Open SAR Toolkit, version ${OST_VERSION}"
+	echo -e " Download Sentinel-1 data from ASF server using an OST inventory shapefile"
+	echo -e "---------------------------------------------------------------------------"
 	echo -e ""
 	echo -e " syntax: oft-sar-S1-ASF-download <output_folder> <Inventory Shapefile>"
 	echo -e ""
 	echo -e " input parameters:"
-	echo -e " output_folder			(output) folder where the downloaded data will be saved"
-	echo -e " Inventory shapefile		(input) shapefile created and maybe edited from oft-sar-ALOS-ASF-inventory script"
+	echo -e "  Output Folder			(output) folder where the downloaded data will be saved"
+	echo -e "  Inventory shapefile		(input) shapefile created and maybe edited from oft-sar-ALOS-ASF-inventory script"
 	exit 1
-else
-	echo -e "----------------------------------"
-	echo -e " Open Foris SAR Toolkit, version ${OSK_VERSION}"
-	echo -e " Download ALOS data from ASF server using an OFST inventory shapefile"
-	echo -e "----------------------------------"
 
-  	cd $1
-  	PROC_DIR=`pwd`
-	TMP_DIR=${PROC_DIR}/.TMP
-	rm -rf ${TMP_DIR} > /dev/null
-	mkdir -p ${TMP_DIR}
+else
 
 	# source libs
 	source ${OPENSARKIT}/lib/helpers_source
+
+	cd $1
+  PROC_DIR=`pwd`
+	TMP_DIR=${PROC_DIR}/.TMP
+	#rm -rf ${TMP_DIR} > /dev/null
+	mkdir -p ${TMP_DIR}
+
+	echo -e "---------------------------------------------------------------------------"  | tee -a ${PROC_DIR}/.s1_dow_progress
+	echo -e " Open SAR Toolkit, version ${OST_VERSION}"  | tee -a ${PROC_DIR}/.s1_dow_progress
+	echo -e " Download Sentinel-1 data from ASF server using an OST inventory shapefile"  | tee -a ${PROC_DIR}/.s1_dow_progress
+	echo -e "---------------------------------------------------------------------------"  | tee -a ${PROC_DIR}/.s1_dow_progress
+
 fi
-
-
 
 if [ "$#" == "3" ];then
 
@@ -93,14 +88,14 @@ else
 fi
 
 echo ""
-echo -ne " Preparing download ..."
+echo -ne " Preparing the download ..." | tee -a ${PROC_DIR}/.s1_dow_progress
 SECONDS=0
 ogrinfo $2 -al | grep Product_ID | sed 's/  Product_ID (String) = //g' | tail -n +2 > ${TMP_DIR}/tmp_download_list &&
 ogrinfo $2 -al | grep Track | sed 's/  Track (Integer) = //g' | tail -n +2 > ${TMP_DIR}/tmp_track_list &&
 ogrinfo $2 -al | grep Orbit_Dir | sed 's/  Orbit_Dir (String) = //g' | tail -n +2 | cut -c -1 > ${TMP_DIR}/tmp_orb_dir_list &&
 ogrinfo $2 -al | grep Date | sed 's/  Date (Integer) = //g'| tail -n +2 > ${TMP_DIR}/tmp_date_list
 ogrinfo $2 -al | grep Scene_ID | sed 's/  Scene_ID (String) = //g' | tail -n +2 > ${TMP_DIR}/scene_id
-duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"
+duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)" | tee -a ${PROC_DIR}/.s1_dow_progress
 echo ""
 
 # counter for info on number of download products
@@ -128,26 +123,53 @@ while read line; do
 	i=1
 	echo "bla" > ${TMP_DIR}/tmp_error
 	#do the loop
+	j=1
 	for(( i=1; i<=2; i++ ));do
 
 		i=3
 		SECONDS=0
-		echo -ne " Downloading Product ${COUNT} of ${NR} (Granule: ${SCENE})... " &&
-		wget -c -P ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/ "${LINK}" >> ${TMP_DIR}/log_download_${COUNT} 2>&1
-		if [ $? -ne 0 ]; then
-			i=1 && echo -e " failed, having another try."
+		echo -ne " Downloading Product ${COUNT} of ${NR} (Granule: ${SCENE})... " | tee -a ${PROC_DIR}/.s1_dow_progress
+		wget --show-progress --progress=dot -q -c -P ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/ "${LINK}" >> ${TMP_DIR}/log_download_${COUNT} 2>&1
+		WGET_ERR=$?
+
+		# wget --show-progress --progress=dot -q -c -P ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/ "${LINK}" >> ${TMP_DIR}/log_download_${COUNT} 2>&1; WGET_ERR=$?) &
+		#  for ((k=1; k<=3; k++));do
+		# 	# get the percentage
+		# 	PERC_DOW=$(cat ${TMP_DIR}/log_download_${COUNT} log_download_1 | tail -n 2 | head -n 1 | awk '{print $7}')
+		# 	echo -e "\e[0K\r Downloading Product ${COUNT} of ${NR} (Granule: ${SCENE})...${PERC_DOW} " | tee -a ${PROC_DIR}/.s1_dow_progress
+		#
+		# 	if [ -z ${WGET_ERR} ];then
+		# 		k=5
+		# 		unset ${WGET_ERR}
+		# 	else
+		# 		k=1
+		# 	fi
+		# done
+
+
+		if [ ${WGET_ERR} == 6 ]; then
+			echo -e ""
+			echo " Username/Password Authentication Failed."  | tee -a ${PROC_DIR}/.s1_dow_progress
+			rm -rf ${TMP_DIR} && exit 2
+		elif [ ${WGET_ERR} -ne 0 ]; then
+			i=1 && echo -e " failed, having another try."  | tee -a ${PROC_DIR}/.s1_dow_progress
+			j=$(expr $j + 1)
+			if [ $j -gt 50 ];then
+				echo -e ""
+				echo " Tried more then 50 times downloading the scene. Exiting because of download problems."  | tee -a ${PROC_DIR}/.s1_dow_progress
+				rm -rf ${TMP_DIR} && exit 3
+			fi
 		else
-				duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"
+				duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"  | tee -a ${PROC_DIR}/.s1_dow_progress
 
 				SECONDS=0
-				echo -ne " Check for Zip archive file integrity..."
+				echo -ne " Checking for Zip archive file integrity..."  | tee -a ${PROC_DIR}/.s1_dow_progress
 				if 7z t ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/${SCENE}.zip | grep "Everything is Ok" > /dev/null;then
-					duration=$SECONDS && echo -e " passed ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"
+					duration=$SECONDS && echo -e " passed ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"  | tee -a ${PROC_DIR}/.s1_dow_progress
 				else
-					i=3
-					duration=$SECONDS && echo -e " failed. Will restart download. ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"
+					i=1
+					duration=$SECONDS && echo -e " failed. Will restart download. ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"  | tee -a ${PROC_DIR}/.s1_dow_progress
 					rm -f ${PROC_DIR}/DATA/${TRACK}${ORB_DIR}/${DATE}"-"${TRACK}${ORB_DIR}/${SCENE}.zip
-					COUNT=`expr ${COUNT} - 1`
 				fi
 
 		fi
@@ -158,8 +180,8 @@ while read line; do
 
 done < ${TMP_DIR}/tmp_list
 
-echo "---------------------------------------------"
-echo " Download of all products succesfully completed"
-echo "---------------------------------------------"
+echo "------------------------------------------------" | tee -a ${PROC_DIR}/.s1_dow_progress
+echo " Download of all products succesfully completed"  | tee -a ${PROC_DIR}/.s1_dow_progress
+echo "------------------------------------------------" | tee -a ${PROC_DIR}/.s1_dow_progress
 
 rm -rf ${TMP_DIR}
diff --git a/bins/Sentinel1/ost_S1_grd2rtc b/bins/Sentinel1/ost_S1_grd2rtc
--- a/bins/Sentinel1/ost_S1_grd2rtc
+++ b/bins/Sentinel1/ost_S1_grd2rtc
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 # The MIT License (MIT)
-# Copyright (c) 2016 Andreas Vollrath
+# written by Andreas Vollrath, 2016
 
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -26,7 +26,7 @@ if [ "$#" != "3" ]; then
 
 	echo -e ""
 	echo -e "----------------------------------------------------------------------------------"
-	echo -e " Open Foris SAR Toolkit, version ${OSK_VERSION}"
+	echo -e " Open SAR Toolkit, version ${OST_VERSION}"
 	echo -e " Preprocess Sentinel-1 GRD scene to a radiometrically terrain corrected product"
 	echo -e "----------------------------------------------------------------------------------"
 	echo -e ""
@@ -45,17 +45,10 @@ if [ "$#" != "3" ]; then
 	echo -e "			  Available choices:"
 	echo -e "			  HI_RES (10m output) "
 	echo -e "			  MED_RES (30m output)"
-#	echo -e "  elevation	(optional) filename to the digital elevation model"
-#	echo -e ""
-#	echo -e "  NOTE: The DEM file should be provided in Geotiff-format as a 16Bit Integer data type with 0 as the no data value."
 	echo -e ""
 	exit 1
-else
-	echo -e "----------------------------------------------------------------------------------"
-	echo -e " Open Foris SAR Toolkit, version ${OSK_VERSION}"
-	echo -e " Preprocess a Sentinel-1 GRD scene to a radiometrically terrain corrected product"
-	echo -e "----------------------------------------------------------------------------------"
 
+else
 
 	# set up initial script variables
 	FILE=`readlink -f $1`
@@ -71,47 +64,63 @@ else
 
 	# source libs
 	source ${OPENSARKIT}/lib/helpers_source
+
+	echo -e "----------------------------------------------------------------------------------" | tee ${PROC_DIR}/.s1_g2r_progress
+	echo -e " Open SAR Toolkit, version ${OST_VERSION}" | tee -a ${PROC_DIR}/.s1_g2r_progress
+	echo -e " Preprocess a Sentinel-1 GRD scene to a radiometrically terrain corrected product" | tee -a ${PROC_DIR}/.s1_g2r_progress
+	echo -e "----------------------------------------------------------------------------------" | tee -a ${PROC_DIR}/.s1_g2r_progress
+
 fi
 
+# Check if RAM disk is applicable
+set_tmp_S1_RTC_bulk 1 ${RESOLUTION} | tee -a ${PROC_DIR}/.s1_g2g_progress
+
 # get scene infos
+s1_info ${FILE} >> ${PROC_DIR}/.s1_g2r_progress
+# we call it a second time to get the exported variables such as SCENE_ID
 s1_info ${FILE}
 
 if [[ ${FILE} == *imported_subset.dim ]];then
 
 	SECONDS=0
-	echo -ne " Applying the Lee Sigma Speckle Filter ..."
+	echo -ne " Applying the Lee Sigma Speckle Filter ..." | tee -a ${PROC_DIR}/.s1_g2r_progress
 	bash ${SNAP_EXE} Speckle-Filter -Ssource=${FILE} -t ${TMP_DIR}/${SCENE_ID}"_speckle" > /dev/null 2>&1
-	duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"
+	duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)" | tee -a ${PROC_DIR}/.s1_g2r_progress
 
 	s1_rtc_processing ${TMP_DIR}/${SCENE_ID}"_speckle.dim" ${OUT_DIR}/${SCENE_ID} ${RESOLUTION} 0 dummyfoo ${TMP_DIR} ${OUT_DIR}
 	rm -rf ${TMP_DIR}/${SCENE_ID}"_speckle"*
 else
-	s1_frame_import ${FILE} ${TMP_DIR}/${SCENE_ID}"_import" ${OUT_DIR}
+	s1_frame_import ${FILE} ${TMP_DIR}/${SCENE_ID}"_import" ${OUT_DIR} | tee -a ${PROC_DIR}/.s1_g2r_progress
 
 	SECONDS=0
-	echo -ne " Applying the Lee Sigma Speckle Filter ..."
+	echo -ne " Applying the Lee Sigma Speckle Filter ..." | tee -a ${PROC_DIR}/.s1_g2r_progress
 	bash ${SNAP_EXE} Speckle-Filter -Ssource=${TMP_DIR}/${SCENE_ID}"_import.dim" -t ${TMP_DIR}/${SCENE_ID}"_speckle" > /dev/null 2>&1
-	duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"
+	duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)" | tee -a ${PROC_DIR}/.s1_g2r_progress
 	rm -rf ${TMP_DIR}/${SCENE_ID}"_import"*
 
-	s1_rtc_processing ${TMP_DIR}/${SCENE_ID}"_speckle.dim" ${OUT_DIR}/${SCENE_ID} ${RESOLUTION} 0 dummyfoo ${TMP_DIR} ${OUT_DIR}
+	s1_rtc_processing ${TMP_DIR}/${SCENE_ID}"_speckle.dim" ${OUT_DIR}/${SCENE_ID} ${RESOLUTION} 0 dummyfoo ${TMP_DIR} ${OUT_DIR} | tee -a ${PROC_DIR}/.s1_g2r_progress
 	rm -rf ${TMP_DIR}/${SCENE_ID}"_speckle"*
 fi
 
 if [[ ${POL_MODE} == "SDV" ]];then
 	SECONDS=0
-	echo -ne " Creating final output file (Band 1: VV, Band 2: VH, Band 3 VV/VH ratio) ..."
+	echo -ne " Creating final output file (Band 1: VV, Band 2: VH, Band 3 VV/VH ratio) ..." | tee -a ${PROC_DIR}/.s1_g2r_progress
 	gdal_merge.py -o ${OUT_DIR}/${SCENE_ID}".RTC".tif -n 0 -a_nodata 0 -separate ${TMP_DIR}/${SCENE_ID}".RTC".data/Gamma0_VV_db.img ${TMP_DIR}/${SCENE_ID}".RTC".data/Gamma0_VH_db.img ${TMP_DIR}/${SCENE_ID}".RTC".data/VV-VH_ratio.img > $OUT_DIR/log_export 2>&1
-  duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"
+  duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)" | tee -a ${PROC_DIR}/.s1_g2r_progress
 
 elif [[ ${POL_MODE} == "SSV" ]];then
 	SECONDS=0
-	echo -ne " Creating final output file (Band 1: VV) ..."
-	gdal_translate -a_nodata 0 ${TMP_DIR}/${SCENE_ID}".RTC".data/Gamma0_VV_db.img ${OUT_DIR}/${SCENE_ID}".RTC".tif > $OUT_DIR/log_export 2>&1
-  duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)"
+	echo -ne " Creating final output file (Band 1: VV) ..." | tee -a ${PROC_DIR}/.s1_g2r_progress
+	gdal_translate -a_nodata 0 -co "COMPRESS=LZW" -co "BIGTIFF=YES" ${TMP_DIR}/${SCENE_ID}".RTC".data/Gamma0_VV_db.img ${OUT_DIR}/${SCENE_ID}".RTC".tif > $OUT_DIR/log_export 2>&1
+  duration=$SECONDS && echo -e " done ($(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed)" | tee -a ${PROC_DIR}/.s1_g2r_progress
 fi
 
 rm -rf ${TMP_DIR}
-echo "------------------------------------------------"
-echo " Succesfully processed ${SCENE_ID}"
-echo "------------------------------------------------"
+
+if [ -e ${OUT_DIR}/${SCENE_ID}".RTC".tif ];then
+	echo "------------------------------------------------" | tee -a ${PROC_DIR}/.s1_g2r_progress
+	echo " Succesfully processed ${SCENE_ID}" | tee -a ${PROC_DIR}/.s1_g2r_progress
+	echo "------------------------------------------------" | tee -a ${PROC_DIR}/.s1_g2r_progress
+else
+	echo "Processing failed for some reason." && exit 1
+fi
